/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Stats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'closedOrders' : IDL.Nat,
  'completeDelivery' : IDL.Nat,
  'pendingDelivery' : IDL.Nat,
  'bricksDue' : IDL.Nat,
  'totalDueAmount' : IDL.Nat,
});
export const UpdateStatRequest = IDL.Record({
  'totalOrders' : IDL.Opt(IDL.Nat),
  'closedOrders' : IDL.Opt(IDL.Nat),
  'completeDelivery' : IDL.Opt(IDL.Nat),
  'pendingDelivery' : IDL.Opt(IDL.Nat),
  'bricksDue' : IDL.Opt(IDL.Nat),
  'totalDueAmount' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'decrementField' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'incrementField' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateStats' : IDL.Func([UpdateStatRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Stats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'closedOrders' : IDL.Nat,
    'completeDelivery' : IDL.Nat,
    'pendingDelivery' : IDL.Nat,
    'bricksDue' : IDL.Nat,
    'totalDueAmount' : IDL.Nat,
  });
  const UpdateStatRequest = IDL.Record({
    'totalOrders' : IDL.Opt(IDL.Nat),
    'closedOrders' : IDL.Opt(IDL.Nat),
    'completeDelivery' : IDL.Opt(IDL.Nat),
    'pendingDelivery' : IDL.Opt(IDL.Nat),
    'bricksDue' : IDL.Opt(IDL.Nat),
    'totalDueAmount' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'decrementField' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'incrementField' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateStats' : IDL.Func([UpdateStatRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };